// Top 100 most popular stock symbols and their companies
export const popularStocks = [
  { symbol: "AAPL", name: "Apple Inc." },
  { symbol: "MSFT", name: "Microsoft Corporation" },
  { symbol: "GOOG", name: "Alphabet Inc. Class C" },
  { symbol: "GOOGL", name: "Alphabet Inc. Class A" },
  { symbol: "AMZN", name: "Amazon.com, Inc." },
  { symbol: "NVDA", name: "NVIDIA Corporation" },
  { symbol: "META", name: "Meta Platforms, Inc." },
  { symbol: "TSLA", name: "Tesla, Inc." },
  { symbol: "BRK.B", name: "Berkshire Hathaway Inc." },
  { symbol: "LLY", name: "Eli Lilly and Company" },
  { symbol: "V", name: "Visa Inc." },
  { symbol: "UNH", name: "UnitedHealth Group Incorporated" },
  { symbol: "JPM", name: "JPMorgan Chase & Co." },
  { symbol: "WMT", name: "Walmart Inc." },
  { symbol: "XOM", name: "Exxon Mobil Corporation" },
  { symbol: "JNJ", name: "Johnson & Johnson" },
  { symbol: "MA", name: "Mastercard Incorporated" },
  { symbol: "PG", name: "The Procter & Gamble Company" },
  { symbol: "HD", name: "The Home Depot, Inc." },
  { symbol: "AVGO", name: "Broadcom Inc." },
  { symbol: "MRK", name: "Merck & Co., Inc." },
  { symbol: "CVX", name: "Chevron Corporation" },
  { symbol: "PEP", name: "PepsiCo, Inc." },
  { symbol: "COST", name: "Costco Wholesale Corporation" },
  { symbol: "KO", name: "The Coca-Cola Company" },
  { symbol: "ABBV", name: "AbbVie Inc." },
  { symbol: "BAC", name: "Bank of America Corporation" },
  { symbol: "ADBE", name: "Adobe Inc." },
  { symbol: "MCD", name: "McDonald's Corporation" },
  { symbol: "TMO", name: "Thermo Fisher Scientific Inc." },
  { symbol: "CSCO", name: "Cisco Systems, Inc." },
  { symbol: "CRM", name: "Salesforce, Inc." },
  { symbol: "ACN", name: "Accenture plc" },
  { symbol: "ABT", name: "Abbott Laboratories" },
  { symbol: "AMD", name: "Advanced Micro Devices, Inc." },
  { symbol: "DHR", name: "Danaher Corporation" },
  { symbol: "NFLX", name: "Netflix, Inc." },
  { symbol: "DIS", name: "The Walt Disney Company" },
  { symbol: "WFC", name: "Wells Fargo & Company" },
  { symbol: "TXN", name: "Texas Instruments Incorporated" },
  { symbol: "INTC", name: "Intel Corporation" },
  { symbol: "CMCSA", name: "Comcast Corporation" },
  { symbol: "ORCL", name: "Oracle Corporation" },
  { symbol: "INTU", name: "Intuit Inc." },
  { symbol: "VZ", name: "Verizon Communications Inc." },
  { symbol: "PM", name: "Philip Morris International Inc." },
  { symbol: "AMGN", name: "Amgen Inc." },
  { symbol: "IBM", name: "International Business Machines Corporation" },
  { symbol: "NKE", name: "NIKE, Inc." },
  { symbol: "UNP", name: "Union Pacific Corporation" },
  { symbol: "HON", name: "Honeywell International Inc." },
  { symbol: "RTX", name: "Raytheon Technologies Corporation" },
  { symbol: "CAT", name: "Caterpillar Inc." },
  { symbol: "QCOM", name: "QUALCOMM Incorporated" },
  { symbol: "LOW", name: "Lowe's Companies, Inc." },
  { symbol: "MS", name: "Morgan Stanley" },
  { symbol: "GS", name: "The Goldman Sachs Group, Inc." },
  { symbol: "SPGI", name: "S&P Global Inc." },
  { symbol: "BLK", name: "BlackRock, Inc." },
  { symbol: "AMAT", name: "Applied Materials, Inc." },
  { symbol: "PLD", name: "Prologis, Inc." },
  { symbol: "T", name: "AT&T Inc." },
  { symbol: "SBUX", name: "Starbucks Corporation" },
  { symbol: "DE", name: "Deere & Company" },
  { symbol: "ADP", name: "Automatic Data Processing, Inc." },
  { symbol: "MDLZ", name: "Mondelez International, Inc." },
  { symbol: "NEE", name: "NextEra Energy, Inc." },
  { symbol: "BKNG", name: "Booking Holdings Inc." },
  { symbol: "ADI", name: "Analog Devices, Inc." },
  { symbol: "SCHW", name: "The Charles Schwab Corporation" },
  { symbol: "GILD", name: "Gilead Sciences, Inc." },
  { symbol: "AMT", name: "American Tower Corporation" },
  { symbol: "ISRG", name: "Intuitive Surgical, Inc." },
  { symbol: "PFE", name: "Pfizer Inc." },
  { symbol: "TJX", name: "The TJX Companies, Inc." },
  { symbol: "NOW", name: "ServiceNow, Inc." },
  { symbol: "ETN", name: "Eaton Corporation plc" },
  { symbol: "LRCX", name: "Lam Research Corporation" },
  { symbol: "ZTS", name: "Zoetis Inc." },
  { symbol: "CVS", name: "CVS Health Corporation" },
  { symbol: "C", name: "Citigroup Inc." },
  { symbol: "MMM", name: "3M Company" },
  { symbol: "AXP", name: "American Express Company" },
  { symbol: "TGT", name: "Target Corporation" },
  { symbol: "PYPL", name: "PayPal Holdings, Inc." },
  { symbol: "TMUS", name: "T-Mobile US, Inc." },
  { symbol: "BABA", name: "Alibaba Group Holding Limited" },
  { symbol: "TSMC", name: "Taiwan Semiconductor Manufacturing Company" },
  { symbol: "BP.L", name: "BP p.l.c." },
  { symbol: "VOD.L", name: "Vodafone Group Plc" },
  { symbol: "TM", name: "Toyota Motor Corporation" },
  { symbol: "7203.T", name: "Toyota Motor Corporation" },
  { symbol: "9984.T", name: "SoftBank Group Corp." },
  { symbol: "0700.HK", name: "Tencent Holdings Limited" },
  { symbol: "9988.HK", name: "Alibaba Group Holding Limited" },
  { symbol: "TSM", name: "Taiwan Semiconductor Manufacturing Company Limited" },
  { symbol: "FB", name: "Meta Platforms, Inc. (formerly Facebook)" },
  { symbol: "BRK-B", name: "Berkshire Hathaway Inc." },
  { symbol: "BRK-A", name: "Berkshire Hathaway Inc." }
];

// Function to search through the popular stocks
export function searchStocks(query: string) {
  if (!query) return [];
  
  const upperQuery = query.toUpperCase();
  
  return popularStocks.filter(stock => 
    stock.symbol.includes(upperQuery) || 
    stock.name.toUpperCase().includes(upperQuery)
  ).slice(0, 10); // Limit to 10 results for performance
}