// List of popular stock symbols and their names
export const topStocks = [
  // US Large Cap Tech Stocks
  { value: "AAPL", label: "Apple Inc." },
  { value: "MSFT", label: "Microsoft Corporation" },
  { value: "AMZN", label: "Amazon.com Inc." },
  { value: "GOOGL", label: "Alphabet Inc. (Google) Class A" },
  { value: "GOOG", label: "Alphabet Inc. (Google) Class C" },
  { value: "META", label: "Meta Platforms Inc." },
  { value: "TSLA", label: "Tesla Inc." },
  { value: "NVDA", label: "NVIDIA Corporation" },
  { value: "AMD", label: "Advanced Micro Devices Inc." },
  { value: "INTC", label: "Intel Corporation" },
  { value: "CRM", label: "Salesforce Inc." },
  { value: "ADBE", label: "Adobe Inc." },
  { value: "CSCO", label: "Cisco Systems Inc." },
  { value: "ORCL", label: "Oracle Corporation" },
  { value: "IBM", label: "International Business Machines" },
  
  // US Large Cap Finance
  { value: "JPM", label: "JPMorgan Chase & Co." },
  { value: "BAC", label: "Bank of America Corporation" },
  { value: "WFC", label: "Wells Fargo & Company" },
  { value: "C", label: "Citigroup Inc." },
  { value: "GS", label: "Goldman Sachs Group Inc." },
  { value: "MS", label: "Morgan Stanley" },
  { value: "BLK", label: "BlackRock Inc." },
  { value: "AXP", label: "American Express Company" },
  
  // US Large Cap Healthcare
  { value: "JNJ", label: "Johnson & Johnson" },
  { value: "UNH", label: "UnitedHealth Group Incorporated" },
  { value: "PFE", label: "Pfizer Inc." },
  { value: "ABBV", label: "AbbVie Inc." },
  { value: "MRK", label: "Merck & Co. Inc." },
  { value: "LLY", label: "Eli Lilly and Company" },
  { value: "ABT", label: "Abbott Laboratories" },
  { value: "TMO", label: "Thermo Fisher Scientific Inc." },
  { value: "DHR", label: "Danaher Corporation" },
  
  // US Large Cap Consumer
  { value: "PG", label: "Procter & Gamble Company" },
  { value: "KO", label: "Coca-Cola Company" },
  { value: "PEP", label: "PepsiCo Inc." },
  { value: "WMT", label: "Walmart Inc." },
  { value: "COST", label: "Costco Wholesale Corporation" },
  { value: "HD", label: "Home Depot Inc." },
  { value: "MCD", label: "McDonald's Corporation" },
  { value: "NKE", label: "NIKE Inc." },
  { value: "SBUX", label: "Starbucks Corporation" },
  
  // US Large Cap Industrial & Energy
  { value: "XOM", label: "Exxon Mobil Corporation" },
  { value: "CVX", label: "Chevron Corporation" },
  { value: "BA", label: "Boeing Company" },
  { value: "CAT", label: "Caterpillar Inc." },
  { value: "GE", label: "General Electric Company" },
  { value: "RTX", label: "Raytheon Technologies" },
  { value: "HON", label: "Honeywell International Inc." },
  
  // Berkshire and others
  { value: "BRK-A", label: "Berkshire Hathaway Inc. Class A" },
  { value: "BRK-B", label: "Berkshire Hathaway Inc. Class B" },
  { value: "V", label: "Visa Inc." },
  { value: "MA", label: "Mastercard Incorporated" },
  { value: "DIS", label: "Walt Disney Company" },
  { value: "NFLX", label: "Netflix Inc." },
  { value: "VZ", label: "Verizon Communications Inc." },
  { value: "T", label: "AT&T Inc." },
  { value: "CMCSA", label: "Comcast Corporation" },
  
  // European stocks
  { value: "BP.L", label: "BP plc (London)" },
  { value: "AZN.L", label: "AstraZeneca plc (London)" },
  { value: "HSBA.L", label: "HSBC Holdings plc (London)" },
  { value: "ULVR.L", label: "Unilever plc (London)" },
  { value: "OR.PA", label: "L'Oréal S.A. (Paris)" },
  { value: "AIR.PA", label: "Airbus SE (Paris)" },
  { value: "SAP.DE", label: "SAP SE (Frankfurt)" },
  { value: "SIE.DE", label: "Siemens AG (Frankfurt)" },
  { value: "SAN.MC", label: "Banco Santander, S.A. (Madrid)" },
  
  // Asian stocks
  { value: "7203.T", label: "Toyota Motor Corporation (Tokyo)" },
  { value: "9984.T", label: "SoftBank Group Corp. (Tokyo)" },
  { value: "6758.T", label: "Sony Group Corporation (Tokyo)" },
  { value: "0700.HK", label: "Tencent Holdings Limited (Hong Kong)" },
  { value: "9988.HK", label: "Alibaba Group Holding Limited (Hong Kong)" },
  { value: "0941.HK", label: "China Mobile Limited (Hong Kong)" },
  { value: "005930.KS", label: "Samsung Electronics Co., Ltd. (Korea)" },
  { value: "2330.TW", label: "Taiwan Semiconductor Manufacturing (Taiwan)" },
  
  // More US tech, mid-caps, and growth
  { value: "PYPL", label: "PayPal Holdings Inc." },
  { value: "BABA", label: "Alibaba Group Holding Limited (US ADR)" },
  { value: "UBER", label: "Uber Technologies Inc." },
  { value: "ABNB", label: "Airbnb Inc." },
  { value: "SQ", label: "Block Inc. (formerly Square)" },
  { value: "COIN", label: "Coinbase Global Inc." },
  { value: "ZM", label: "Zoom Video Communications Inc." },
  { value: "SNAP", label: "Snap Inc." },
  { value: "TWTR", label: "Twitter Inc." },
  { value: "SHOP", label: "Shopify Inc." },
  { value: "NET", label: "Cloudflare Inc." },
  { value: "U", label: "Unity Software Inc." },
  { value: "SNOW", label: "Snowflake Inc." },
  { value: "PLTR", label: "Palantir Technologies Inc." },
  { value: "CRWD", label: "CrowdStrike Holdings Inc." },
  { value: "OKTA", label: "Okta Inc." },
  { value: "DDOG", label: "Datadog Inc." },
  { value: "TEAM", label: "Atlassian Corporation Plc" },
  { value: "ZS", label: "Zscaler Inc." },
  { value: "SPLK", label: "Splunk Inc." },
  { value: "DASH", label: "DoorDash Inc." },
  { value: "RBLX", label: "Roblox Corporation" },
  
  // Electric vehicle and green energy
  { value: "RIVN", label: "Rivian Automotive Inc." },
  { value: "LCID", label: "Lucid Group Inc." },
  { value: "NIO", label: "NIO Inc." },
  { value: "FSLR", label: "First Solar Inc." },
  { value: "ENPH", label: "Enphase Energy Inc." },
  { value: "SEDG", label: "SolarEdge Technologies Inc." },
  
  // Semiconductors
  { value: "TSM", label: "Taiwan Semiconductor Manufacturing (US ADR)" },
  { value: "AVGO", label: "Broadcom Inc." },
  { value: "TXN", label: "Texas Instruments Incorporated" },
  { value: "QCOM", label: "QUALCOMM Incorporated" },
  { value: "MU", label: "Micron Technology Inc." },
  { value: "ADI", label: "Analog Devices Inc." },
  { value: "AMAT", label: "Applied Materials Inc." },
  { value: "LRCX", label: "Lam Research Corporation" },
  { value: "KLAC", label: "KLA Corporation" },
];

export default topStocks;